### ISSUE TITLE
加个油

### ISSUE THREAD

**Issue by ACrsm** [Bian-Sh/TinyRPC#1]
大佬加油， 希望客户端网络能支持 http,kcp。 同时也方便移植到其他项目。

**Comment by Bian-Sh** [comment]
http 不是 UnityWebRequest 本身就支持了嘛？

**Comment by Bian-Sh** [comment]
实不相瞒，暂时是没有支持 kcp 的计划哎，但是你可以 fork 后开发呀

**Comment by Bian-Sh** [comment]
或者有什么沟通啊指导啊啥的可以言无不尽哈，欢迎探讨~
